const translations = {
  id: {
    appSubtitle: 'Route Creator',
    badgeBryton: 'Bryton Rider Format',
    badgeOsm: 'OSM Road Snap',
    badgeVercel: 'Vercel Ready',
    panelHeader: 'Panel',
    minimizePanel: 'Minimize Panel',
    uploadTitle: 'Unggah File GPX',
    uploadHintClick: 'Klik untuk memilih',
    uploadHintOrDrag: 'atau seret file .gpx ke sini',
    uploadHintSupport: 'Mendukung file GPX dari Strava, Komoot, Garmin, OSM, dll.',
    changeFile: 'Ganti file',
    routeToolsTitle: 'Alat Rute Tambahan',
    btnSimplifyRdp: 'Optimasi Garis Lurus (RDP)',
    rdpDesc: 'Membuang titik berlebih di jalur lurus untuk meringankan ukuran file tanpa mengubah bentuk asli rute.',
    tbtTitle: 'Advanced Options',
    generateCardTitle: 'Generate Turn By Turn',
    tbtOsmAuto: 'GraphHopper Turn-by-Turn',
    tbtOsmDesc: 'Mengambil instruksi belokan & nama jalan otomatis dari GraphHopper API.',
    angleThreshold: 'Sudut Belokan Tambahan',
    angleDesc: 'Jika ada belokan ≥ sudut ini yang belum ada di OSM, belokan baru akan ditambahkan otomatis. Jika sudah ada di OSM, tidak diduplikasi.',
    dupRadius: 'Radius Proteksi Duplikasi',
    dupDesc: 'Jarak toleransi (meter) agar belokan sudut tidak menduplikasi belokan yang sudah terdaftar di OSM.',
    smoothRadius: 'Filter GPS Noise (Smoothing)',
    smoothDesc: 'Menghindari deteksi belokan palsu akibat jitter/noise sinyal GPS.',
    btnProcess: 'Generate Turn By Turn',
    downloadTitle: 'Unduh Rute',
    routeNameLabel: 'Nama Rute',
    routeNamePlaceholder: 'Contoh: Gowes Sentul 50km',
    btnDownloadZip: 'Download Bryton Route (.ZIP)',
    guideTitle: 'Cara Pasang di Head Unit Bryton:',
    guide1: 'Ekstrak file .zip hasil download.',
    guide2: 'Hubungkan Bryton Rider ke Komputer via kabel USB.',
    guide3: 'Buka folder Bryton &rarr; tracks di dalam storage perangkat.',
    guide4: 'Salin semua file dan folder hasil ekstraksi ke folder tracks tersebut.',
    guide5: 'Cabut aman (Eject), buka menu Follow Track / Ikuti Rute di Bryton Anda!',
    btnSaveDb: 'Simpan Rute',
    btnDownloadBryton: 'Bryton (.ZIP)',
    btnDownloadFit: 'FIT',
    btnShareBrytonActive: 'Bagikan ke Bryton Active',
    btnDownloadKml: 'KML',
    btnDownloadGpx: 'GPX',
    btnDownloadMenu: 'Pilih Format Unduhan',
    btnViewRoute: 'Lihat',
    btnDeleteRoute: 'Hapus',
    confirmDeleteRoute: 'Hapus rute ini?',
    confirmOverwriteRoute: 'Rute sudah ada di peta. Mengupload GPX baru akan menghapus rute saat ini. Lanjutkan?',
    saveRouteTitle: 'Simpan Rute',
    elevationChartTitle: 'Profil Elevasi',
    alertDeleteFailed: 'Gagal menghapus: ',
    statDist: 'Jarak Total',
    statPoints: 'Titik Koordinat',
    statOsm: 'Belokan OSM',
    statAngle: 'Belokan Sudut',
    statTotal: 'Total Instruksi',
    btnEditModeOn: 'Mode Edit Rute',
    btnEditModeOff: 'Batalkan Edit',
    btnCreateRoute: 'Buat Rute Manual',
    btnEndRoute: 'Selesai Buat Rute',
    btnUndo: 'Undo',
    btnRedo: 'Redo',
    btnShowPanel: 'Tampilkan',
    btnHidePanel: 'Sembunyikan',
    btnSaveEdit: 'Simpan Perubahan',
    btnAddTurn: 'Tambah Belokan',
    editHint: 'KLIK & GESER marker putih untuk mengubah rute. KLIK garis biru (atau peta) untuk tambah titik. KLIK KANAN marker untuk hapus.',
    chkGraphHopperTbt: 'Ambil dari GraphHopper',
    modalTitleTbt: 'Tambah Belokan (TBT)',
    turnDirectionLabel: 'Arah Belokan',
    turnNameLabel: 'Nama Jalan / Instruksi',
    turnNamePlaceholder: 'Contoh: Jl. Sudirman',
    btnCancel: 'Batal',
    btnAdd: 'Tambahkan',
    modalTitlePoi: 'Tambah POI',
    poiIconLabel: 'Ikon POI',
    poiNameLabel: 'Nama POI',
    poiNamePlaceholder: 'Contoh: Warung Kopi',
    modalEditTitleTbt: 'Edit Belokan',
    btnSave: 'Simpan',
    modalEditTitlePoi: 'Edit POI',
    modalEditTitleClimb: 'Edit Tanjakan',
    climbNameLabel: 'Nama Tanjakan',
    optStraight: 'Lurus (Go Ahead)',
    optRight: 'Belok Kanan',
    optLeft: 'Belok Kiri',
    optSlightRight: 'Serong Kanan',
    optSlightLeft: 'Serong Kiri',
    optSharpRight: 'Belok Tajam Kanan',
    optSharpLeft: 'Belok Tajam Kiri',
    optExitRight: 'Exit Kanan',
    optExitLeft: 'Exit Kiri',
    optUturnRight: 'Putar Balik Kanan',
    optUturnLeft: 'Putar Balik Kiri',
    optKeepRight: 'Tetap di Kanan',
    optKeepLeft: 'Tetap di Kiri',
    optRampRight: 'Ramp Kanan',
    optRampLeft: 'Ramp Kiri',
    optMerge: 'Bergabung (Merge)',
    optRoundaboutRight: 'Bundaran Kanan',
    optRoundaboutLeft: 'Bundaran Kiri',
    optFerry: 'Kapal Feri',
    optFerryTrain: 'Kapal Feri / Kereta',
    optVia: 'Titik Singgah (Via)',
    optEnterRoundabout: 'Masuk Bundaran',
    optLeaveRoundabout: 'Keluar Bundaran',
    optFinish: 'Tujuan (Finish)',
    createHint: 'Klik pada peta untuk menggambar rute dari nol.',
    autoSnapLabel: 'Auto Snap Jalan',
    turnsTableTitle: 'Daftar Instruksi Turn-by-Turn',
    turnHeaderDir: 'Arah',
    turnHeaderInst: 'Instruksi / Nama Jalan',
    turnHeaderSrc: 'Sumber',
    turnHeaderDist: 'Jarak (m)',
    turnHeaderEst: 'Estimasi',
    turnHeaderCoord: 'Koordinat',
    turnHeaderAction: 'Aksi',
    emptyTable: 'Belum ada data turn-by-turn. Silakan upload file GPX terlebih dahulu.',
    noTurnsDetected: 'Tidak ada belokan terdeteksi.',
    startRoute: 'Mulai Perjalanan',
    badgeOsm: 'OSM',
    badgeExtra: 'Sudut',
    toastLocError: 'Gagal mendapatkan lokasi Anda. Pastikan izin GPS (Lokasi) diaktifkan di browser.',
    toastFormatGpx: 'Harap pilih file dengan format .gpx!',
    toastGpxLoaded: 'File GPX dimuat! Klik "Analisis & Generate Route"',
    toastGpxInvalid: 'Format GPX tidak valid atau tidak memiliki titik koordinat.',
    toastSmoothing: 'Sedang melakukan smoothing jalan OSM (Anti-Double Track)...',
    toastSmoothSuccess: 'Smoothing presisi jalan berhasil tanpa double jalur!',
    toastSnapFailed: 'Gagal melakukan snap jalan, menggunakan koordinat GPX asli.',
    toastUploadFirstEdit: 'Upload file GPX terlebih dahulu untuk mengedit rute.',
    toastEditModeOn: 'Mode Edit Aktif: Geser / Kanan-Klik marker, atau KLIK garis biru (atau peta) untuk tambah titik.',
    toastRoutingNewPoint: 'Membuat rute ke titik baru...',
    toastUndo: 'Undo berhasil',
    toastRedo: 'Redo berhasil',
    toastRouteUpdated: 'Rute berhasil diperbarui!',
    toastUploadFirst: 'Upload file GPX terlebih dahulu.',
    toastClickManualTurn: 'Klik pada garis rute di peta untuk memasang belokan manual.',
    toastStartPointAdded: 'Titik awal rute ditambahkan!',
    toastRoutingRoad: 'Merutekan ke jalan...',
    toastPointSnapped: 'Titik ditambahkan (Snap ke Jalan)!',
    toastPointOffroad: 'Titik lurus ditambahkan (Offroad)!',
    toastClickMapManual: 'Klik pada peta untuk mulai menggambar rute manual.',
    toastAnalyzing: 'Sedang menganalisis rute & mendeteksi belokan...',
    toastFetchGH: 'Mengambil data jalan dari GraphHopper API...',
    toastAnalyzeFirst: 'Silakan lakukan analisis rute terlebih dahulu.',
    toastCreatingZip: 'Sedang membuat file ZIP Bryton...',
    toastZipSuccess: 'Download ZIP berhasil! Silakan salin file ke Bryton Anda.',
    toastPointAddedIndex: 'Titik baru ditambahkan di indeks #{idx}!',
    toastTurnAdded: 'Belokan manual "{text}" berhasil ditambahkan!',
    toastAnalysisDone: 'Analisis selesai! Terdeteksi {count} instruksi turn-by-turn.',
    toastAnalyzeError: 'Terjadi kesalahan saat analisis: ',
    toastRdpNoRoute: 'Pilih rute terlebih dahulu.',
    toastRdpConfirm: 'Apakah Anda yakin ingin membuang titik lurus yang berlebihan? Tindakan ini akan mengoptimasi rute secara permanen.',
    toastRdpSuccess: 'Optimasi: {0} titik lurus dibuang.',
    toastRdpNoOp: 'Rute sudah optimal, tidak ada titik lurus yang dibuang.',
    toastTurnDeleted: 'Belokan "{text}" dihapus.',
    toastZipError: 'Gagal membuat ZIP: ',
    btnShowPanel: 'Tampilkan',
    btnHidePanel: 'Sembunyikan',
    badgeManual: 'Manual',
    delTurnTitle: 'Hapus belokan ini',
    popupSource: 'Sumber:',
    popupDistance: 'Jarak ke belokan berikut:',
    modalTitle: 'Tambah Belokan Manual',
    modalCoord: 'Koordinat:',
    modalDir: 'Arah Belokan',
    modalInst: 'Nama Jalan / Instruksi (Opsional)',
    modalInstPlaceholder: 'Contoh: Jl. Sudirman',
    modalBtnCancel: 'Batal',
    modalBtnAdd: 'Tambahkan',
    btnCancelAddTurn: 'Batalkan Tambah Belokan',
    // Turn directions
    dirSharpLeft: 'Belok Tajam Kiri',
    dirLeft: 'Belok Kiri',
    dirSlightLeft: 'Serong Kiri',
    dirStraight: 'Lurus',
    dirSlightRight: 'Serong Kanan',
    dirRight: 'Belok Kanan',
    dirSharpRight: 'Belok Tajam Kanan',
    dirUturn: 'Putar Balik (U-Turn)',
    poiFood: '🍴 Food',
    poiWater: '💧 Waypoint',
    poiSummit: '⛺ Peak',
    poiGroup: '👥 Meeting Point',
    poiSprint: '⚡ Start Point',
    poiFirstAid: '➕ Emergency',
    poiCheck: '☑️ Checkpoint',
    poiTarget: '🎯 End Point',
    mapTitle: 'Visualisasi Rute',
    btnLocateMe: 'Pergi ke Lokasi Saat Ini',
    btnUndoEdit: 'Undo (Ctrl+Z)',
    btnRedoEdit: 'Redo (Ctrl+Y)',
    modeCreateActive: 'Mode Buat Rute Aktif: Klik pada peta untuk menggambar.',
    modeAddTurnActive: 'Mode Tambah Belokan Aktif: Klik pada garis rute di peta untuk memasang belokan manual. Klik lagi tombol untuk membatalkan.',
    chkSnapToRoad: 'Snap to Road (OSM)',
    mapPlaceholderText: 'Unggah file GPX atau klik <strong>Buat Rute Manual</strong> untuk memulai',
    legendOsm: 'OSM Turn (Cyan)',
    legendExtra: 'Extra Angle Turn (Orange)',
    legendTrack: 'Track Path (Blue)',
    layerHint: 'Gunakan ikon layer di pojok kanan atas peta untuk beralih ke <strong>Satelit</strong> / <strong>CyclOSM</strong> / <strong>Street</strong>.',
    turnCounterBadge: '0 Instruksi',
    instructionCountWord: 'Instruksi',
    btnMinimizeTable: 'Minimize Tabel',
    climbTitle: 'Kriteria Deteksi Tanjakan',
    climbMinDist: 'Jarak Minimal',
    climbMinGrade: 'Grade Rata-rata Minimal',
    climbMinScore: 'Skor Tanjakan (Jarak x Grade)',
    btnAddPoi: 'Tambah POI',
    tabTurns: 'Turn-by-Turn',
    tabPois: 'POI',
    tabClimbs: 'Climb',
    poiHeaderIcon: 'Ikon',
    poiHeaderName: 'Nama POI',
    emptyPois: 'Belum ada data POI.',
    climbHeaderIcon: 'Aksi',
    climbHeaderName: 'Nama Tanjakan',
    climbHeaderGrade: 'Grade (%)',
    emptyClimbs: 'Belum ada data Tanjakan.',
    climbPrefix: 'Tanjakan',
    btnRoundTrip: 'Round Trip (Loop)',
    modalTitleRoundTrip: 'Buat Round Trip Otomatis',
    rtStartPoint: 'Titik Awal (Start/Finish)',
    rtStartHint: 'Pilih titik di peta atau masukkan koordinat',
    rtPickOnMap: 'Pilih di Peta',
    rtPickingMap: 'Klik di Peta...',
    rtDistance: 'Perkiraan Jarak Target',
    rtHeading: 'Arah Awal (Heading)',
    rtHeadingHint: 'Arah keberangkatan dari titik awal',
    rtHeadingDeg: 'derajat',
    rtProfile: 'Mode Rute',
    rtProfileBike: 'Sepeda (Bike)',
    rtProfileRoad: 'Sepeda Balap (Road Bike)',
    rtProfileMtb: 'Sepeda Gunung (MTB)',
    rtProfileFoot: 'Lari / Jalan (Foot)',
    rtNewSeed: 'Acak Variasi Rute',
    btnGenerateRoundTrip: 'Generate Round Trip',
    rtModeActive: 'Mode Pilih Titik Awal Round Trip Aktif: Silakan klik di peta.',
    toastRtNoPoint: 'Silakan tentukan titik awal di peta terlebih dahulu.',
    toastRtGenerating: 'Menghitung rute round trip dari GraphHopper...',
    toastRtSuccess: 'Rute round trip berhasil dibuat!',
    // Additional dual language keys
    navCreate: 'Buat Rute',
    navMyRoutes: 'Rute Saya',
    loginWelcome: 'Selamat datang di OpenBryton',
    loginDesc: 'Aplikasi andalan Anda untuk menyelaraskan (snap) rute GPX ke jalan OSM, merencanakan Turn-by-Turn, dan mengekspor sempurna ke perangkat Bryton.',
    loginWithGoogle: 'Lanjutkan dengan Google',
    btnLogoutTitle: 'Keluar (Logout)',
    btnUploadGpxToolbar: 'Upload GPX',
    btnUploadGpxTitle: 'Upload file GPX',
    btnCloseRoute: 'Tutup Rute',
    btnCloseRouteTitle: 'Tutup Rute (Sambung ke Titik Awal)',
    btnSimplifyRdpTitle: 'Optimasi Garis Lurus (RDP)',
    btnRoundTripTitle: 'Buat Rute Round Trip (Loop)',
    btnSaveRouteEdit: 'Selesai & Update Rute',
    mySavedRoutesTitle: 'Rute Tersimpan Saya',
    emptyMyRoutes: 'Tidak ada rute ditemukan.',
    loadingRoutes: 'Memuat rute...',
    failedLoadingRoutes: 'Gagal memuat: ',
    cardDistanceLabel: 'Jarak',
    cardElevationLabel: 'Elevasi',
    cardUploadedOn: 'Diunggah pada',
    cardBy: 'oleh',
    cardJustNow: 'Baru saja',
    alertDemoModeLogin: "Mode Demo aktif (Firebase belum di-setup). Login berhasil sebagai 'Goweser Lokal'.",
    alertLoginFailed: 'Login gagal: ',
    alertNeedLogin: 'Silakan login terlebih dahulu.',
    alertNoRouteToSave: 'Tidak ada rute untuk disimpan.',
    alertRouteSaved: 'Rute berhasil disimpan!',
    alertSaveFailed: 'Gagal menyimpan rute: ',
    alertRouteNotFound: 'Rute tidak ditemukan.',
    alertEditorNotReady: 'Fungsi editor belum siap. Silakan muat ulang halaman.',
    alertLoadRouteFailed: 'Gagal memuat rute: ',
    savingRouteText: 'Menyimpan...',
    confirmSwitchRoute: 'Anda sedang memiliki rute yang terbuka. Membuat rute baru akan mereset data rute saat ini di layar. Lanjutkan?',
    confirmManualRouteStart: 'Memulai rute manual akan menghapus rute yang ada di peta saat ini. Lanjutkan?',
    confirmRoundTripStart: 'Membuat rute round trip baru akan menimpa rute yang ada di peta saat ini. Lanjutkan?',
    toastRouteLoadedEditor: 'Rute dimuat ke Editor!',
    toastViewOnlyMode: 'Mode Lihat: Hanya bisa mengunduh',
    toastNeed2PointsToClose: 'Rute harus memiliki minimal 2 titik untuk bisa ditutup.',
    toastRouteAlreadyClosed: 'Rute sudah tertutup (Loop).',
    toastClosingRouteSnap: 'Menutup rute ke titik awal (Snap)...',
    toastRouteClosedSuccess: 'Rute berhasil ditutup (Loop)!',
    toastRouteCloseFailed: 'Gagal menutup rute.',
    toastGhFetching: 'Mengambil instruksi dari GraphHopper...',
    toastGhNoTurn: 'GraphHopper: Tidak ada instruksi belokan di titik ini',
    toastGhFailed: 'Gagal memanggil GraphHopper',
    toastStartSetGps: 'Titik awal disetel ke lokasi GPS Anda.',
    toastSearchingGps: 'Mencari sinyal lokasi GPS...',
    toastSeedUpdated: 'Variasi acak diperbarui (Seed: {seed})',
    toastRoundTripFailed: 'Gagal membuat Round Trip: ',
    toastFitSuccess: 'Download file FIT berhasil!',
    toastFitFailed: 'Gagal memproses file FIT: ',
    toastUploadingTemp: 'Mengunggah ke server sementara...',
    toastOpeningBrytonActive: 'Membuka Bryton Active...',
    toastGpxDownloaded: 'File GPX berhasil diunduh!',
    toastKmlDownloaded: 'File KML berhasil diunduh!',
    btnAddPoiToolbar: 'Tambah POI',
    btnCancelAddPoiToolbar: 'Batal Tambah POI',
    modeAddPoiActive: 'Mode Tambah POI Aktif: Klik pada rute untuk meletakkan POI.',
    closeModalTitle: 'Tutup',
    useMyLocationTitle: 'Gunakan Lokasi Saya',
    headingNorth: 'Utara',
    headingNorthEast: 'Timur Laut',
    headingEast: 'Timur',
    headingSouthEast: 'Tenggara',
    headingSouth: 'Selatan',
    headingSouthWest: 'Barat Daya',
    headingWest: 'Barat',
    headingNorthWest: 'Barat Laut',
    climbStartSuffix: 'Mulai',
    climbEndSuffix: 'Selesai'
  },
  en: {
    appSubtitle: 'Route Creator',
    badgeBryton: 'Bryton Rider Format',
    badgeOsm: 'OSM Road Snap',
    badgeVercel: 'Vercel Ready',
    panelHeader: 'Panel',
    minimizePanel: 'Minimize Panel',
    uploadTitle: 'Upload GPX File',
    uploadHintClick: 'Click to select',
    uploadHintOrDrag: 'or drag .gpx file here',
    uploadHintSupport: 'Supports GPX files from Strava, Komoot, Garmin, OSM, etc.',
    changeFile: 'Change file',
    routeToolsTitle: 'Route Tools',
    btnSimplifyRdp: 'Straight Line Optimization (RDP)',
    rdpDesc: 'Removes redundant points on straight lines to reduce file size without changing the route shape.',
    tbtTitle: 'Advanced Options',
    generateCardTitle: 'Generate Turn By Turn',
    tbtOsmAuto: 'GraphHopper Turn-by-Turn',
    tbtOsmDesc: 'Automatically retrieves turn instructions and street names from GraphHopper API.',
    angleThreshold: 'Extra Turn Angle Threshold',
    angleDesc: 'If a turn ≥ this angle is missing in OSM, a new turn will be added automatically. Duplicates are prevented if it already exists.',
    dupRadius: 'Duplicate Protection Radius',
    dupDesc: 'Tolerance distance (meters) to prevent angle-based turns from duplicating existing OSM turns.',
    smoothRadius: 'GPS Noise Filter (Smoothing)',
    smoothDesc: 'Prevents false turn detection caused by GPS signal jitter/noise.',
    btnProcess: 'Generate Turn By Turn',
    downloadTitle: 'Download Route',
    routeNameLabel: 'Route Name',
    routeNamePlaceholder: 'e.g., Sunday Ride 50km',
    btnDownloadZip: 'Download Bryton Route (.ZIP)',
    guideTitle: 'How to Install on Bryton Head Unit:',
    guide1: 'Extract the downloaded .zip file.',
    guide2: 'Connect your Bryton Rider to the Computer via USB cable.',
    guide3: 'Open the Bryton &rarr; tracks folder in the device storage.',
    guide4: 'Copy all extracted file and folder into the tracks folder.',
    guide5: 'Safely Eject, open the Follow Track menu on your Bryton!',
    btnSaveDb: 'Save Route',
    btnDownloadBryton: 'Bryton (.ZIP)',
    btnDownloadFit: 'FIT',
    btnShareBrytonActive: 'Share to Bryton Active',
    btnDownloadKml: 'KML',
    btnDownloadGpx: 'GPX',
    btnDownloadMenu: 'Select Download Format',
    btnViewRoute: 'View',
    btnDeleteRoute: 'Delete',
    confirmDeleteRoute: 'Delete this route?',
    confirmOverwriteRoute: 'A route is already loaded on the map. Uploading a new GPX will overwrite the current route. Continue?',
    saveRouteTitle: 'Save Route',
    elevationChartTitle: 'Elevation Profile',
    alertDeleteFailed: 'Failed to delete: ',
    statDist: 'Total Distance',
    statPoints: 'Coordinates',
    statOsm: 'OSM Turns',
    statAngle: 'Angle Turns',
    statTotal: 'Total Instructions',
    btnEditModeOn: 'Edit Route Mode',
    btnEditModeOff: 'Cancel Edit',
    btnCreateRoute: 'Create Manual Route',
    btnEndRoute: 'Finish Route',
    btnUndo: 'Undo',
    btnRedo: 'Redo',
    btnShowPanel: 'Show',
    btnHidePanel: 'Hide',
    btnSaveEdit: 'Save Changes',
    btnAddTurn: 'Add Turn',
    editHint: 'CLICK & DRAG white markers to change route. CLICK blue line (or map) to add a point. RIGHT CLICK marker to delete.',
    chkGraphHopperTbt: 'Fetch from GraphHopper',
    modalTitleTbt: 'Add Turn (TBT)',
    turnDirectionLabel: 'Turn Direction',
    turnNameLabel: 'Street Name / Instruction',
    turnNamePlaceholder: 'e.g., Main Street',
    btnCancel: 'Cancel',
    btnAdd: 'Add',
    modalTitlePoi: 'Add POI',
    poiIconLabel: 'POI Icon',
    poiNameLabel: 'POI Name',
    poiNamePlaceholder: 'e.g., Coffee Shop',
    modalEditTitleTbt: 'Edit Turn',
    btnSave: 'Save',
    modalEditTitlePoi: 'Edit POI',
    modalEditTitleClimb: 'Edit Climb',
    climbNameLabel: 'Climb Name',
    optStraight: 'Straight (Go Ahead)',
    optRight: 'Turn Right',
    optLeft: 'Turn Left',
    optSlightRight: 'Slight Right',
    optSlightLeft: 'Slight Left',
    optSharpRight: 'Sharp Right',
    optSharpLeft: 'Sharp Left',
    optExitRight: 'Exit Right',
    optExitLeft: 'Exit Left',
    optUturnRight: 'U-Turn Right',
    optUturnLeft: 'U-Turn Left',
    optKeepRight: 'Keep Right',
    optKeepLeft: 'Keep Left',
    optRampRight: 'Ramp Right',
    optRampLeft: 'Ramp Left',
    optMerge: 'Merge',
    optRoundaboutRight: 'Roundabout Right',
    optRoundaboutLeft: 'Roundabout Left',
    optFerry: 'Ferry',
    optFerryTrain: 'Ferry/Train',
    optVia: 'Via',
    optEnterRoundabout: 'Enter Roundabout',
    optLeaveRoundabout: 'Leave Roundabout',
    optFinish: 'Finish',
    createHint: 'Click on the map to draw a route from scratch.',
    autoSnapLabel: 'Auto Snap to Roads',
    turnsTableTitle: 'Turn-by-Turn Instructions List',
    turnHeaderDir: 'Direction',
    turnHeaderInst: 'Instruction / Street Name',
    turnHeaderSrc: 'Source',
    turnHeaderDist: 'Distance (m)',
    turnHeaderEst: 'Estimate',
    turnHeaderCoord: 'Coordinates',
    turnHeaderAction: 'Action',
    emptyTable: 'No turn-by-turn data available. Please upload a GPX file first.',
    noTurnsDetected: 'No turns detected.',
    startRoute: 'Start Route',
    badgeOsm: 'OSM',
    badgeExtra: 'Angle',
    toastLocError: 'Failed to get location. Ensure GPS permission is enabled in browser.',
    toastFormatGpx: 'Please select a .gpx file!',
    toastGpxLoaded: 'GPX loaded! Click "Analyze & Generate Route"',
    toastGpxInvalid: 'Invalid GPX format or missing coordinates.',
    toastSmoothing: 'Performing OSM road smoothing (Anti-Double Track)...',
    toastSmoothSuccess: 'Precision road smoothing successful without double tracks!',
    toastSnapFailed: 'Road snap failed, using original GPX coordinates.',
    toastUploadFirstEdit: 'Upload a GPX file first to edit the route.',
    toastEditModeOn: 'Edit Mode Active: Drag / Right-Click markers, or CLICK the blue line (or map) to add points.',
    toastRoutingNewPoint: 'Routing to new point...',
    toastUndo: 'Undo successful',
    toastRedo: 'Redo successful',
    toastRouteUpdated: 'Route successfully updated!',
    toastUploadFirst: 'Please upload a GPX file first.',
    toastClickManualTurn: 'Click on the route line on the map to place a manual turn.',
    toastStartPointAdded: 'Route start point added!',
    toastRoutingRoad: 'Routing to road...',
    toastPointSnapped: 'Point added (Snapped to Road)!',
    toastPointOffroad: 'Straight point added (Offroad)!',
    toastClickMapManual: 'Click on the map to start drawing a manual route.',
    toastAnalyzing: 'Analyzing route & detecting turns...',
    toastFetchGH: 'Fetching street data from GraphHopper API...',
    toastAnalyzeFirst: 'Please analyze the route first.',
    toastCreatingZip: 'Creating Bryton ZIP file...',
    toastZipSuccess: 'ZIP Download successful! Please copy the files to your Bryton.',
    toastPointAddedIndex: 'New point added at index #{idx}!',
    toastTurnAdded: 'Manual turn "{text}" successfully added!',
    toastAnalysisDone: 'Analysis complete! {count} turn-by-turn instructions detected.',
    toastAnalyzeError: 'An error occurred during analysis: ',
    toastRdpNoRoute: 'Please select a route first.',
    toastRdpConfirm: 'Are you sure you want to remove redundant straight points? This will optimize the route permanently.',
    toastRdpSuccess: 'Optimization: {0} straight points removed.',
    toastRdpNoOp: 'Route is already optimized, no straight points were removed.',
    toastTurnDeleted: 'Turn "{text}" deleted.',
    toastZipError: 'Failed to create ZIP: ',
    btnShowPanel: 'Show',
    btnHidePanel: 'Hide',
    badgeManual: 'Manual',
    delTurnTitle: 'Delete this turn',
    popupSource: 'Source:',
    popupDistance: 'Distance to next turn:',
    modalTitle: 'Add Manual Turn',
    modalCoord: 'Coordinates:',
    modalDir: 'Turn Direction',
    modalInst: 'Street Name / Instruction (Optional)',
    modalInstPlaceholder: 'e.g., Main Street',
    modalBtnCancel: 'Cancel',
    modalBtnAdd: 'Add',
    btnCancelAddTurn: 'Cancel Add Turn',
    // Turn directions
    dirSharpLeft: 'Sharp Left',
    dirLeft: 'Left',
    dirSlightLeft: 'Slight Left',
    dirStraight: 'Straight',
    dirSlightRight: 'Slight Right',
    dirRight: 'Right',
    dirSharpRight: 'Sharp Right',
    dirUturn: 'U-Turn',
    poiFood: '🍴 Food',
    poiWater: '💧 Waypoint',
    poiSummit: '⛺ Peak',
    poiGroup: '👥 Meeting Point',
    poiSprint: '⚡ Start Point',
    poiFirstAid: '➕ Emergency',
    poiCheck: '☑️ Checkpoint',
    poiTarget: '🎯 End Point',
    mapTitle: 'Route Visualization',
    btnLocateMe: 'Go to Current Location',
    btnUndoEdit: 'Undo (Ctrl+Z)',
    btnRedoEdit: 'Redo (Ctrl+Y)',
    modeCreateActive: 'Create Route Mode Active: Click on the map to draw.',
    modeAddTurnActive: 'Add Turn Mode Active: Click on the route line to add a manual turn. Click button again to cancel.',
    chkSnapToRoad: 'Snap to Road (OSM)',
    mapPlaceholderText: 'Upload a GPX file or click <strong>Create Manual Route</strong> to start',
    legendOsm: 'OSM Turn (Cyan)',
    legendExtra: 'Extra Angle Turn (Orange)',
    legendTrack: 'Track Path (Blue)',
    layerHint: 'Use the layer icon in the top right corner of the map to switch to <strong>Satellite</strong> / <strong>CyclOSM</strong> / <strong>Street</strong>.',
    turnCounterBadge: '0 Instructions',
    instructionCountWord: 'Instructions',
    btnMinimizeTable: 'Minimize Table',
    climbTitle: 'Climb Detection Criteria',
    climbMinDist: 'Minimum Distance',
    climbMinGrade: 'Minimum Average Grade',
    climbMinScore: 'Climb Score (Dist x Grade)',
    btnAddPoi: 'Add POI',
    tabTurns: 'Turn-by-Turn',
    tabPois: 'POI',
    tabClimbs: 'Climb',
    poiHeaderIcon: 'Icon',
    poiHeaderName: 'POI Name',
    emptyPois: 'No POI data available.',
    climbHeaderIcon: 'Action',
    climbHeaderName: 'Climb Name',
    climbHeaderGrade: 'Grade (%)',
    emptyClimbs: 'No climb data available.',
    climbPrefix: 'Climb',
    btnRoundTrip: 'Round Trip (Loop)',
    modalTitleRoundTrip: 'Generate Auto Round Trip',
    rtStartPoint: 'Starting Point (Start/Finish)',
    rtStartHint: 'Select on map or enter coordinates',
    rtPickOnMap: 'Pick on Map',
    rtPickingMap: 'Click on Map...',
    rtDistance: 'Target Distance',
    rtHeading: 'Initial Heading',
    rtHeadingHint: 'Departure direction from start point',
    rtHeadingDeg: 'degrees',
    rtProfile: 'Routing Mode',
    rtProfileBike: 'Bicycle (Bike)',
    rtProfileRoad: 'Road Bike',
    rtProfileMtb: 'Mountain Bike (MTB)',
    rtProfileFoot: 'Run / Walk (Foot)',
    rtNewSeed: 'Randomize Route Variant',
    btnGenerateRoundTrip: 'Generate Round Trip',
    rtModeActive: 'Round Trip Pick Start Point Active: Click anywhere on the map.',
    toastRtNoPoint: 'Please choose a start point on the map first.',
    toastRtGenerating: 'Calculating round trip route from GraphHopper...',
    toastRtSuccess: 'Round trip route generated successfully!',
    // Additional dual language keys
    navCreate: 'Create',
    navMyRoutes: 'My Routes',
    loginWelcome: 'Welcome to OpenBryton',
    loginDesc: 'Your ultimate companion for snapping GPX routes to OSM roads, planning Turn-by-Turn, and exporting perfectly to Bryton devices.',
    loginWithGoogle: 'Continue with Google',
    btnLogoutTitle: 'Logout',
    btnUploadGpxToolbar: 'Upload GPX',
    btnUploadGpxTitle: 'Upload GPX file',
    btnCloseRoute: 'Close Route',
    btnCloseRouteTitle: 'Close Route (Connect to Start)',
    btnSimplifyRdpTitle: 'Straight Line Optimization (RDP)',
    btnRoundTripTitle: 'Create Round Trip Route (Loop)',
    btnSaveRouteEdit: 'Finish & Update Route',
    mySavedRoutesTitle: 'My Saved Routes',
    emptyMyRoutes: 'No routes found.',
    loadingRoutes: 'Loading routes...',
    failedLoadingRoutes: 'Failed to load: ',
    cardDistanceLabel: 'Distance',
    cardElevationLabel: 'Elevation',
    cardUploadedOn: 'Uploaded on',
    cardBy: 'by',
    cardJustNow: 'Just now',
    alertDemoModeLogin: "Demo Mode active (Firebase not configured). Logged in as 'Goweser Lokal'.",
    alertLoginFailed: 'Login failed: ',
    alertNeedLogin: 'Please login first.',
    alertNoRouteToSave: 'No route to save.',
    alertRouteSaved: 'Route saved successfully!',
    alertSaveFailed: 'Failed to save route: ',
    alertRouteNotFound: 'Route not found.',
    alertEditorNotReady: 'Editor is not ready yet. Please refresh the page.',
    alertLoadRouteFailed: 'Failed to load route: ',
    savingRouteText: 'Saving...',
    confirmSwitchRoute: 'You currently have an active route open. Starting a new route will reset current route data. Continue?',
    confirmManualRouteStart: 'Starting a manual route will overwrite the current route on the map. Continue?',
    confirmRoundTripStart: 'Generating a new round trip will overwrite the current route on the map. Continue?',
    toastRouteLoadedEditor: 'Route loaded to Editor!',
    toastViewOnlyMode: 'View Mode: Download only',
    toastNeed2PointsToClose: 'Route must have at least 2 points to be closed.',
    toastRouteAlreadyClosed: 'Route is already closed (Loop).',
    toastClosingRouteSnap: 'Closing route to start point (Snap)...',
    toastRouteClosedSuccess: 'Route successfully closed (Loop)!',
    toastRouteCloseFailed: 'Failed to close route.',
    toastGhFetching: 'Fetching instructions from GraphHopper...',
    toastGhNoTurn: 'GraphHopper: No turn instructions at this point',
    toastGhFailed: 'Failed to call GraphHopper',
    toastStartSetGps: 'Start point set to your GPS location.',
    toastSearchingGps: 'Searching for GPS location signal...',
    toastSeedUpdated: 'Random variation updated (Seed: {seed})',
    toastRoundTripFailed: 'Failed to generate Round Trip: ',
    toastFitSuccess: 'FIT file downloaded successfully!',
    toastFitFailed: 'Failed to process FIT file: ',
    toastUploadingTemp: 'Uploading to temporary server...',
    toastOpeningBrytonActive: 'Opening Bryton Active...',
    toastGpxDownloaded: 'GPX file downloaded successfully!',
    toastKmlDownloaded: 'KML file downloaded successfully!',
    btnAddPoiToolbar: 'Add POI',
    btnCancelAddPoiToolbar: 'Cancel Add POI',
    modeAddPoiActive: 'Add POI Mode Active: Click on the route to place a POI.',
    closeModalTitle: 'Close',
    useMyLocationTitle: 'Use My Location',
    headingNorth: 'North',
    headingNorthEast: 'North East',
    headingEast: 'East',
    headingSouthEast: 'South East',
    headingSouth: 'South',
    headingSouthWest: 'South West',
    headingWest: 'West',
    headingNorthWest: 'North West',
    climbStartSuffix: 'Start',
    climbEndSuffix: 'End'
  }
};

let currentLang = localStorage.getItem('openbryton_lang') || 'id';

function t(key) {
  if (translations[currentLang] && translations[currentLang][key] !== undefined) {
    return translations[currentLang][key];
  }
  if (translations['id'] && translations['id'][key] !== undefined) {
    return translations['id'][key];
  }
  return key;
}

function switchLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('openbryton_lang', lang);
  updateDOMText();

  // Re-render JS dynamic text (e.g. table if points exist)
  if (typeof updateStatsAndUI === 'function') {
    updateStatsAndUI();
  }
  if (typeof loadMyRoutes === 'function' && document.getElementById('page-myroutes')?.classList.contains('active')) {
    loadMyRoutes();
  }
  if (typeof updateRoundTripUI === 'function') {
    updateRoundTripUI();
  }
}

function updateDOMText() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const val = t(key);
    if (val && val !== key) {
      if (el.hasAttribute('data-i18n-html')) {
        el.innerHTML = val;
      } else {
        el.textContent = val;
      }
    }
  });

  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.getAttribute('data-i18n-title');
    const val = t(key);
    if (val && val !== key) {
      el.title = val;
    }
  });

  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    const val = t(key);
    if (val && val !== key) {
      el.placeholder = val;
    }
  });

  // Need to recreate lucide icons if we overwrote innerHTML
  if (typeof lucide !== 'undefined') {
    lucide.createIcons();
  }
}

function updateLangDropdownUI() {
  const btnIcon = document.getElementById('currentLangIcon');
  const btnText = document.getElementById('currentLangText');
  const options = document.querySelectorAll('.lang-option');

  if (btnIcon && btnText) {
    if (currentLang === 'id') {
      btnIcon.className = 'fi fi-id';
      btnText.textContent = 'ID';
    } else {
      btnIcon.className = 'fi fi-gb';
      btnText.textContent = 'EN';
    }
  }

  options.forEach(opt => {
    if (opt.getAttribute('data-value') === currentLang) {
      opt.classList.add('active');
    } else {
      opt.classList.remove('active');
    }
  });
}

function initLangDropdown() {
  const dropdown = document.getElementById('langDropdown');
  const btn = document.getElementById('langDropdownBtn');
  const options = document.querySelectorAll('.lang-option');

  if (!dropdown || !btn) return;

  // Toggle dropdown
  btn.addEventListener('click', (e) => {
    e.stopPropagation();
    dropdown.classList.toggle('open');
  });

  // Close when clicking outside
  document.addEventListener('click', (e) => {
    if (!dropdown.contains(e.target)) {
      dropdown.classList.remove('open');
    }
  });

  // Handle option click
  options.forEach(opt => {
    opt.addEventListener('click', (e) => {
      const val = opt.getAttribute('data-value');
      if (val !== currentLang) {
        switchLanguage(val);
      }
      dropdown.classList.remove('open');
    });
  });

  updateLangDropdownUI();
}

// Override switchLanguage to also update UI
const originalSwitchLanguage = switchLanguage;
window.switchLanguage = function (lang) {
  originalSwitchLanguage(lang);
  updateLangDropdownUI();
};

// Initial setup
document.addEventListener('DOMContentLoaded', () => {
  updateDOMText();
  initLangDropdown();
});
